[tool.ruff]
# ターゲットとするPythonのバージョン
target-version = "py310"

# 行の最大長
line-length = 100

# 未使用インポートを自動的に削除
fix = true

# ソースコードのエンコーディング
src = ["*.py"]

[tool.ruff.lint]
# 検出するルールセット
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "N",  # pep8-naming
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
]

# 無視するルール
ignore = []

[tool.ruff.lint.isort]
# isort設定
known-first-party = ["tello_control", "video_stream"]

[tool.black]
# Blackの設定
line-length = 100
target-version = ["py310"]
include = '\.pyi?$'
extend-exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | build
  | dist
)/
'''